version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    volumes:
      - .:/app
    networks:
      - go-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html/public
    depends_on:
      - app
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
